name: Fierbase Hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build project
        working-directory:  front-end
        run: |
          yarn install
          yarn build

      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.3
        working-directory:  front-end
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: shanika-wijerathna

